name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicfurnaces.EpicFurnaces
softdepend:
  - BentoBox
  - DecentHolograms
  - FabledSkyBlock
  - Factions
  - GriefPrevention
  - HolographicDisplays
  - Lands
  - PlotSquared
  - RedProtect
  - SkyBlock
  - USkyBlock
  - UltimateClaims
  - Vault
  - WorldGuard

author: Songoda
website: ${project.url}

commands:
  EpicFurnaces:
    aliases:
      - ef
